package com.imfundokahle.service;

import org.springframework.stereotype.Service;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

@Service
public class MotivationalQuoteService {
    private final Random random = new Random();

    private static final List<String> STUDENT_QUOTES = Arrays.asList(
        "El aprendizaje es un tesoro que te seguira adonde vayas.",
        "El exito es la suma de pequenos esfuerzos repetidos dia tras dia.",
        "Cree en ti mismo y en lo que eres. Eres mas grande que cualquier obstaculo.",
        "No te canses de aprender, porque la vida no se cansa de ensenar.",
        "Tu actitud determina tu altitud.",
        "La educacion es el pasaporte hacia el futuro.",
        "Hoy un lector, manana un lider.",
        "Los errores son pruebas de que estas intentando.",
        "La mente que se abre a una nueva idea jamas vuelve a su tamano original.",
        "Cada vez que aprendes algo nuevo, te conviertes en alguien nuevo.",
        "El unico lugar donde el exito viene antes que el trabajo es en el diccionario.",
        "El genio se hace con un 1% de talento y un 99% de trabajo.",
        "Preguntate si lo que estas haciendo hoy te acerca al lugar en el que quieres estar manana.",
        "Nunca consideres el estudio como una obligacion, sino como una oportunidad.",
        "Lo que aprendes hoy, sera tu superpoder manana.",
        "Un idioma diferente es una vision diferente de la vida.",
        "Conocer otro idioma es poseer una segunda alma.",
        "El limite de tu lenguaje es el limite de tu mundo.",
        "No importa que tan lento vayas, siempre y cuando no te detengas.",
        "Un viaje de mil millas comienza con un solo paso.",
        "Aprender es descubrir que algo es posible.",
        "Si crees que puedes, ya estas a medio camino.",
        "El conocimiento te dara poder, el caracter te dara respeto.",
        "No se trata de ser el mejor, se trata de ser mejor que ayer.",
        "Todo experto fue alguna vez un principiante.",
        "Siempre parece imposible hasta que se hace.",
        "No midas tu progreso por la regla de los demas.",
        "Cada pequeno paso te acerca a tu gran meta.",
        "Esfuerzate, porque nadie mas lo hara por ti.",
        "Si no vas detras de lo que quieres, nunca lo tendras.",
        "Haz de hoy una obra maestra.",
        "No desistas, los mejores comienzos vienen despues de los peores finales.",
        "Se tu mayor competencia.",
        "Haz algo hoy por lo que tu yo del futuro te agradezca.",
        "Nada es un error si aprendes de ello.",
        "Las raices de la educacion son amargas, pero el fruto es dulce.",
        "Aprender es un regalo, incluso cuando el dolor es tu maestro.",
        "Transforma el 'no puedo' en 'como puedo'.",
        "Tu unico limite es tu mente.",
        "Persiste, insiste y nunca desistas.",
        "Las oportunidades no ocurren, tu las creas.",
        "Si puedes sonarlo, puedes hacerlo.",
        "El esfuerzo de hoy es el exito de manana.",
        "Invierte en ti mismo, es la mejor inversion que haras.",
        "El universo premia a los que no se rinden.",
        "La constancia vence al talento cuando el talento no es constante.",
        "Aprender idiomas es abrir puertas que ni siquiera sabias que existian.",
        "Tu potencial es infinito, empieza a explorarlo.",
        "Un nuevo vocabulario es una nueva forma de pensar.",
        "Celebra cada pequeno logro, estas mas cerca que ayer."
    );

    private static final List<String> TEACHER_QUOTES = Arrays.asList(
        "Ensenar es aprender dos veces.",
        "El arte de ensenar es el arte de asistir el descubrimiento.",
        "Un buen maestro puede inspirar esperanza, encender la imaginacion e inculcar amor por el aprendizaje.",
        "Educar la mente sin educar el corazon no es educacion en absoluto.",
        "La influencia de un buen maestro jamas se borra.",
        "Tu labor no es llenar una cubeta, sino encender un fuego.",
        "Los maestros plantan semillas que crecen para siempre.",
        "Lo que el maestro es, es mas importante que lo que ensena.",
        "Un profesor afecta la eternidad; nadie puede decir donde termina su influencia.",
        "Ensenar es dejar una huella en la vida de una persona.",
        "Gracias por ser la brujula que guia a tus estudiantes.",
        "El trabajo del maestro no es ensenar todo, sino inspirar a aprender.",
        "Detras de cada estudiante exitoso, hay un maestro que creyo en el.",
        "La paciencia y el amor son tus mejores herramientas en el aula.",
        "No solo ensenas un idioma, ensenas a conectar con el mundo.",
        "Cambias vidas cada vez que entras al salon de clases.",
        "Tu vocacion transforma futuros.",
        "El mayor signo de exito de un profesor es poder decir: 'Los ninos trabajan como si yo no existiera'.",
        "Ensenas hoy el futuro de manana.",
        "Eres el puente entre la duda y el entendimiento.",
        "Un maestro hace que las cosas dificiles parezcan faciles.",
        "Ensenar requiere corazon, y tu tienes uno inmenso.",
        "No todos los superheroes llevan capa, algunos llevan marcadores de pizarra.",
        "El impacto que dejas hoy durara para siempre.",
        "Inspiras porque lideras con el ejemplo.",
        "El entusiasmo es el mejor motor en la ensenanza.",
        "Tus palabras de aliento pueden ser el salvavidas de un alumno.",
        "Ensenar es el mayor acto de optimismo.",
        "Cultivas mentes y abrigas corazones.",
        "Eres un constructor de puentes hacia nuevas culturas.",
        "Un buen maestro escucha lo que el alumno no dice.",
        "Tus clases son ventanas al mundo.",
        "Tienes el poder de despertar la curiosidad.",
        "La motivacion que das hoy es la resiliencia de manana.",
        "Nunca subestimes el poder de una palabra amable en clase.",
        "Eres arquitecto de suenos y forjador de caracteres.",
        "Cada leccion es una oportunidad para maravillar.",
        "Ensenar idiomas es ensenar empatia.",
        "Tu pasion se contagia a tus estudiantes.",
        "Gracias por ser un faro en su aprendizaje.",
        "El aprendizaje florece donde la pasion se siembra.",
        "Haces mas que ensenar, tu empoderas.",
        "Transformas la confusion en claridad.",
        "Tu dedicacion se refleja en el brillo de sus ojos al entender.",
        "Guiar a otros es el honor mas grande.",
        "Eres el eco que resonara en sus futuras decisiones.",
        "El conocimiento compartido es amor multiplicado.",
        "La maestria no esta en saber, sino en saber transmitir.",
        "Eres la clave que abre puertas cerradas al entendimiento.",
        "En cada clase escribes el prologo del futuro."
    );

    private static final List<String> PRACTICANTE_QUOTES = Arrays.asList(
        "El experto de hoy fue el practicante de ayer.",
        "Cada tarea es una oportunidad para demostrar tu talento.",
        "No busques ser exitoso, busca ser valioso.",
        "El aprendizaje practico es la llave del dominio profesional.",
        "Hazlo con pasion o no lo hagas.",
        "Los retos de hoy son la experiencia de manana.",
        "La proactividad te llevara a lugares que no imaginas.",
        "Una actitud positiva lo cambia todo en el trabajo.",
        "Aprende de todo, observa todo, pregunta todo.",
        "Tu frescura y nuevas ideas son un gran aporte al equipo.",
        "El trabajo duro vence al talento cuando el talento no trabaja duro.",
        "Se como una esponja, absorbe todo el conocimiento que puedas.",
        "Los grandes proyectos se construyen con pequenos detalles.",
        "La iniciativa es hacer lo correcto sin que te lo digan.",
        "Cada error es una leccion disfrazada.",
        "Mantente curioso y hambriento por aprender.",
        "El exito se esconde en tu rutina diaria.",
        "Tu esfuerzo esta sembrando tu futuro profesional.",
        "No temas equivocarte, teme no intentarlo.",
        "La confianza se construye con horas de practica.",
        "El trabajo en equipo divide la tarea y multiplica el exito.",
        "Tus habilidades crecen con cada desafio que superas.",
        "Se la energia que quieres atraer al equipo.",
        "El mundo necesita personas que amen lo que hacen.",
        "La excelencia no es un acto, es un habito.",
        "No importa tu nivel, importa tu actitud de mejora.",
        "Demuestra tu valia en los pequenos encargos.",
        "Cada hora invertida es una accion en tu empresa personal.",
        "Transforma tu potencial en poder a traves de la practica.",
        "Acepta el feedback como el desayuno de los campeones.",
        "Eres el motor fresco de esta organizacion.",
        "Donde pones tu atencion, pones tu energia.",
        "La perseverancia es el trabajo duro que haces despues de cansarte.",
        "Crea el habito de dar siempre un poco mas.",
        "Tus metas profesionales empiezan con las tareas de hoy.",
        "Se humilde para aprender y valiente para proponer.",
        "Construyes tu reputacion en cada interaccion.",
        "El exito profesional no se encuentra, se forja.",
        "Tu entusiasmo puede cambiar la dinamica del dia.",
        "El verdadero aprendizaje ocurre fuera de la zona de confort.",
        "Las oportunidades bailan con aquellos que ya estan en la pista.",
        "Toma responsabilidad de tu propio aprendizaje.",
        "Observa a los expertos e imita su disciplina.",
        "Eres una pieza clave, por pequena que parezca la tarea.",
        "Tu dedicacion inspira a los que te rodean.",
        "El profesionalismo es una eleccion diaria.",
        "No midas el valor por el cargo, sino por el impacto.",
        "Eres el puente entre la teoria y el mundo real.",
        "Tu carrera empezo el primer dia que decidiste aprender.",
        "Celebra que hoy eres mas capaz que ayer."
    );

    public String getRandomStudentQuote() { return STUDENT_QUOTES.get(random.nextInt(STUDENT_QUOTES.size())); }
    public String getRandomTeacherQuote() { return TEACHER_QUOTES.get(random.nextInt(TEACHER_QUOTES.size())); }
    public String getRandomPracticanteQuote() { return PRACTICANTE_QUOTES.get(random.nextInt(PRACTICANTE_QUOTES.size())); }
}
